baseURL: https://www.mhaziqrk.uk/
languageCode: en-us
title: Mhaziqrk Blog
theme : PaperMod 
defaultContentLanguage: en

enableRobotsTXT: true

params : 
    env: production
    disableScrollToTop: false
    description: "Daily learn new technology! Deep dive into the world of technology with Haziq Rohaizan. This site is a collection of my notes and thoughts on various topics. I hope you find them useful."
    comments: true

    editPost:
        URL: "https://github.com/mhrk04/mhrk04.github.io/edit/update-papermod/content/"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    keywords: [Blog, Portfolio, Tech, IT, Techtips, Tutorial, Linux, Windows, Android]
    ShowCodeCopyButtons : true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    author: Haziq Rohaizan
    fuseOpts:
            isCaseSensitive: false
            shouldSort: true
            location: 0
            distance: 1000
            threshold: 0.4
            minMatchCharLength: 0
            keys: ["title", "permalink", "summary", "content"]

    socialIcons: # optional
        - name: "Instagram"
          url: "https://www.instagram.com/mhaziqrk/"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/mhaziqrk/"
        - name: "Github"
          url: "https://github.com/mhrk04"
        - name: "X"
          url: "https://twitter.com/haziqrohaizan" 
        - name: "telegram"
          url: "https://t.me/mhrk04"
        - name: "youtube"
          url: "https://www.youtube.com/channel/UCj38keOzG0iHUbgs9vD1HwA"
         
    cover :
      linkFullImages : true
      responsiveImages: true

    profileMode:
        enabled: true
        title: "Mhaziqrk Blog" # optional default will be site title
        subtitle: "Everyday learn new technology!"
        imageUrl: "me.webp" # optional
        # imageTitle: "<title of image as alt>" # optional
        # imageWidth: 120 # custom size
        # imageHeight: 120 # custom size
        buttons:
          - name: Git Notes
            url: "/gitmaster"
          - name: Computer Network Notes
            url: "/net-note"
          - name: OS Admin Note
            url: "/os-admin"
            
        assets:
              # disableHLJS: true # to disable highlight.js
              # disableFingerprinting: true
              favicon: "/favicon.ico"
              favicon16x16: "/favicon.ico"
              favicon32x32: "/favicon.ico"
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

sitemap:
  changefreq: always
  filename: sitemap.xml
  priority: 1.0